### ISSUE TITLE
Re: Digital Information Management

### ISSUE THREAD

**Issue by samirm** [killercup/scribbles#26]
I think you might be looking for something like ontologies and the semantic web. These technologies would let you create objects and their relationships and then automatically apply reasoning to them based on their properties and relationships. It's also the idea that TBL had for the web all along. Exciting stuff :)

**Comment by samirm** [comment]
Btw, do these comments get collected and posted back on their respective pages?

**Comment by killercup** [comment]
Yeah, that goes I to the same direction. Editing data smoothly (having a great UI that fits the current data) and creating new "types" ad-hoc is also a big part of making this convenient. I think. I don't know what I was thinking of precisely, honestly, because that post is almost 10 years old.

(Comments here don't show up on the site automatically)

**Comment by killercup** [comment]
(Closing because it's been a while)
